version: '2'
services:
  m_rsn1:
    container_name: m_rs1n1
    image: mongo
    command: mongod --shardsvr --replSet m_rs1 --dbpath /data/db --port 27017
    ports:
      - 27017:27017
    expose:
      - "27017"
    environment:
      TERM: xterm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mongo_cluster/data1:/data/db
  m_rs1n2:
    container_name: m_rs1n2
    image: mongo
    command: mongod --shardsvr --replSet m_rs1 --dbpath /data/db --port 27017
    ports:
      - 27027:27017
    expose:
      - "27017"
    environment:
      TERM: xterm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mongo_cluster/data2:/data/db
  m_rs1n3:
    container_name: m_rs1n3
    image: mongo
    command: mongod --shardsvr --replSet m_rs1 --dbpath /data/db --port 27017
    ports:
      - 27037:27017
    expose:
      - "27017"
    environment:
      TERM: xterm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mongo_cluster/data3:/data/db
  m_cfg1:
    container_name: m_cfg1
    image: mongo
    command: mongod --configsvr --replSet m_rs1conf --dbpath /data/db --port 27017
    environment:
      TERM: xterm
    expose:
      - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mongo_cluster/config1:/data/db
  m_cfg2:
    container_name: m_cfg2
    image: mongo
    command: mongod --configsvr --replSet m_rs1conf --dbpath /data/db --port 27017
    environment:
      TERM: xterm
    expose:
      - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mongo_cluster/config2:/data/db
  m_cfg3:
    container_name: m_cfg3
    image: mongo
    command: mongod --configsvr --replSet m_rs1conf --dbpath /data/db --port 27017
    environment:
      TERM: xterm
    expose:
      - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mongo_cluster/config3:/data/db
  m_s1:
    container_name: m_s1
    image: mongo
    depends_on:
      - m_cfg1
      - m_cfg2
    command: mongos --bind_ip_all --configdb m_rs1conf/m_cfg1:27017,m_cfg2:27017,m_cfg3:27017 --port 27017
    ports:
      - 27019:27017
    expose:
      - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
  m_s2:
    container_name: m_s2
    image: mongo
    depends_on:
      - m_cfg1
      - m_cfg2
    command: mongos --bind_ip_all --configdb m_rs1conf/m_cfg1:27017,m_cfg2:27017,m_cfg3:27017 --port 27017
    ports:
      - 27020:27017
    expose:
      - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro

